# Generated by Django 5.1.3 on 2024-11-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='text',
            field=models.TextField(verbose_name='Полный текст новости'),
        ),
    ]
